// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	// Example binding to KV. Learn more at https://developers.cloudflare.com/workers/runtime-apis/kv/
	// MY_KV_NAMESPACE: KVNamespace;
	//
	// Example binding to Durable Object. Learn more at https://developers.cloudflare.com/workers/runtime-apis/durable-objects/
	// MY_DURABLE_OBJECT: DurableObjectNamespace;
	//
	// Example binding to R2. Learn more at https://developers.cloudflare.com/workers/runtime-apis/r2/
	// MY_BUCKET: R2Bucket;
	//
	// Example binding to a Service. Learn more at https://developers.cloudflare.com/workers/runtime-apis/service-bindings/
	// MY_SERVICE: Fetcher;
	// Example binding to a Queue. Learn more at https://developers.cloudflare.com/workers/runtime-apis/queues/
	// MY_QUEUE: Queue;
	//
	// Example binding to a Timer. Learn more at https://developers.cloudflare.com/workers/runtime-apis/timers/
	// MY_TIMER: Timer;
	//
	// Example binding to an Event. Learn more at https://developers.cloudflare.com/workers/runtime-apis/events/
}
